version: '3.3'

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres